image: docker:stable
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
services:
  - docker:dind # docker in docker

# **************************************************************************** #
# build
# **************************************************************************** #

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  when: manual # skip 15min, but has to be done manually if Dockerfile changes

# **************************************************************************** #
# test
# **************************************************************************** #

.test: # dot means "hidden", acts as base class
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE:latest # use prebuilt image in Gitlab's registry
    entrypoint: [""] # == Repo. Has to be done if Dockerfile has own entrypoint

test:convergence:heat:
  extends: .test
  script:
    - cd ${TEST_DIRECTORY}/heat
    - ./run_test.sh