version: '3.2'

services:
  fenicsr13_release:
    image: registry.git.rwth-aachen.de/lamboo/fenicsr13:latest
    working_dir: /home/fenics/shared
    volumes:
      - type: bind
        source: .
        target: /home/fenics/shared
      - type: volume
        source: instant-cache
        target: /home/fenics/.cache
        volume:
          nocopy: true
    ports:
      - 127.0.0.1:8000:8000
    stdin_open: true
    tty: true
  fenicsr13_debug:
    build: .
    working_dir: /home/fenics/shared
    volumes:
      - ~/.gitconfig:/etc/gitconfig:ro # copy Git config to commit correctly
      - type: bind
        source: .
        target: /home/fenics/shared
      - type: volume
        source: instant-cache
        target: /home/fenics/.cache
        volume:
          nocopy: true
    ports:
      - 127.0.0.1:8000:8000
    stdin_open: true
    tty: true

volumes:
  instant-cache: