version: '3.2'
services:
  fenics:
    build: .
    working_dir: /home/fenics/shared
    volumes:
      - type: bind
        source: .
        target: /home/fenics/shared
      - type: volume
        source: instant-cache
        target: /home/fenics/.cache
        volume:
          nocopy: true
    stdin_open: true
    tty: true

volumes:
  instant-cache: